site_name: UrMoAC
site_url: https://github.com/DLR-VF/UrMoAC/wiki
site_description: Urban Mobility Accessibility Calculator
site_author: DLR/VF
docs_dir: ./UrMoAC.wiki

repo_url: https://github.com/DLR-VF/UrMoAC.git
edit_uri: ""

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
    palette:
        primary: light green
        
nav:
    - Home: index.md
    - Installation: Installation.md
    - Usage: 
        - Basics: Usage.md
        - Options: Options.md
        - Input Data Formats: InputDataFormats.md
        - Import Scripts: ImportScripts.md
        - Output Formats: OutputFormats.md
        - Visualisation Tools: VisualisationTools.md
    - Tutorials: 
        - Tutorial List: Tutorials.md
        - Computing the accessibility to the next public transport halt: TutorialNextPTHalt.md
        - Using QGIS to visualise UrMoAC results: TutorialQGISVisualisation.md
#    - Methods: 
#        - Outline: Methods.md
#        - Mapping to network: MappingToNet.md
    - ChangeLog: ChangeLog.md
    - Links: Links.md
    - Publications: Publications.md
    - Developer Docs: 
        - Overview: DeveloperDocs.md
        - Testing UrMoAC: DeveloperTests.md
        - Creating a static documentation: DeveloperStaticDocumentation.md
        - How To Release: DeveloperHowToRelease.md
        - Todo: Todo.md
    - Legal: 
        - Main: Legal.md
        - License (EPL v2.0): LICENSE.md
        - Disclaimer: Disclaimer.md

markdown_extensions:
    - admonition
    - sane_lists
  
copyright: "&copy; Copyright 2018&ndash;2023 German Aerospace Center, Institute of Transport Research, all rights reserved."

plugins:
    - search