site_name: UrMoAC
site_url: https://github.com/DLR-VF/UrMoAC/
site_description: Urban Mobility Accessibility Calculator
site_author: DLR/VF
docs_dir: ./mkdocs

repo_url: https://github.com/DLR-VF/UrMoAC.git
edit_uri: ""

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
    palette:
        primary: light green
        
nav:
    - Home: index.md
    - Installation: Installation.md
    - Usage: 
        - Basics: Usage.md
        - Options: Options.md
        - Input Data Formats: InputDataFormats.md
        - Import Scripts: ImportScripts.md
        - Output Formats: OutputFormats.md
        - Visualisation Tools: VisualisationTools.md
    - Tutorials: 
        - Tutorial List: Tutorials.md
        - Computing the accessibility to the next public transport halt: TutorialNextPTHalt.md
        - Using QGIS to visualise UrMoAC results: TutorialQGISVisualisation.md
    - Subtopics:
        - Subtopics List: Subtopics.md
        - Mapping To Net: Subtopic_Mapping.md
    - FAQ: FAQ.md
    - ChangeLog: ChangeLog.md
    - Links: Links.md
    - Publications: Publications.md
    - Included Data: IncludedData.md
    - Included Scripts: IncludedScripts.md
    - Developer Docs: 
        - Overview: DeveloperDocs.md
        - Testing UrMoAC: DeveloperTests.md
        - Building a Static Documentation: DeveloperStaticDocumentation.md
        - How To Release: DeveloperHowToRelease.md
#        - Todo: Todo.md
    - Legal: 
        - Main: Legal.md
        - License (EPL v2.0): LICENSE.md
        - Disclaimer: Disclaimer.md
        - Impressum: Impressum.md

markdown_extensions:
    - admonition
    - sane_lists
  
copyright: "&copy; Copyright 2016&ndash;2023 German Aerospace Center, Institute of Transport Research, all rights reserved."

plugins:
    - search